# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.registerName = QtWidgets.QLineEdit(self.groupBox_7)
        self.registerName.setObjectName("registerName")
        self.verticalLayout_5.addWidget(self.registerName)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.registerUserName = QtWidgets.QLineEdit(self.groupBox_6)
        self.registerUserName.setObjectName("registerUserName")
        self.verticalLayout_6.addWidget(self.registerUserName)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.registerPassWord = QtWidgets.QLineEdit(self.groupBox_5)
        self.registerPassWord.setObjectName("registerPassWord")
        self.verticalLayout_7.addWidget(self.registerPassWord)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.regBtn = QtWidgets.QPushButton(self.groupBox)
        self.regBtn.setObjectName("regBtn")
        self.verticalLayout_2.addWidget(self.regBtn)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 1)
        self.sendLine = QtWidgets.QLineEdit(self.centralwidget)
        self.sendLine.setObjectName("sendLine")
        self.gridLayout.addWidget(self.sendLine, 4, 0, 1, 1)
        self.msg_veiw = QtWidgets.QTextEdit(self.centralwidget)
        self.msg_veiw.setReadOnly(True)
        self.msg_veiw.setObjectName("msg_veiw")
        self.gridLayout.addWidget(self.msg_veiw, 1, 0, 3, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginUserName = QtWidgets.QLineEdit(self.groupBox_4)
        self.loginUserName.setObjectName("loginUserName")
        self.verticalLayout_3.addWidget(self.loginUserName)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.loginPassWord = QtWidgets.QLineEdit(self.groupBox_3)
        self.loginPassWord.setObjectName("loginPassWord")
        self.verticalLayout_4.addWidget(self.loginPassWord)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.logBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.logBtn.setObjectName("logBtn")
        self.verticalLayout.addWidget(self.logBtn)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.sendBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sendBtn.sizePolicy().hasHeightForWidth())
        self.sendBtn.setSizePolicy(sizePolicy)
        self.sendBtn.setObjectName("sendBtn")
        self.gridLayout.addWidget(self.sendBtn, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout.setColumnStretch(0, 5)
        self.gridLayout.setRowStretch(0, 10)
        self.gridLayout.setRowStretch(1, 20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "register"))
        self.groupBox_7.setTitle(_translate("MainWindow", "name (show in chat)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "user name"))
        self.groupBox_5.setTitle(_translate("MainWindow", "password"))
        self.regBtn.setText(_translate("MainWindow", "register"))
        self.groupBox_2.setTitle(_translate("MainWindow", "log in"))
        self.groupBox_4.setTitle(_translate("MainWindow", "user name"))
        self.groupBox_3.setTitle(_translate("MainWindow", "password"))
        self.logBtn.setText(_translate("MainWindow", "log in"))
        self.sendBtn.setText(_translate("MainWindow", "send"))
        self.status.setText(_translate("MainWindow", "you are not  logged in"))

